---
- name: Deploy single node using manifests
  hosts: provisioner
  environment:
    PATH: "/usr/bin/:/usr/local/bin/:{{ ansible_env.PATH }}"
  roles:
    - role: enable-workload-partitioning
    - role: chrony_day0
    - role: deploy_cluster

