---
- name: Remove previous vm
  community.libvirt.virt:
    command: destroy
    name: "{{ item.name }}_{{ cluster_name }}"
    uri: "{{ libvirt_uri }}"
  ignore_errors: true
  with_items: "{{ groups['master_nodes'] }}"

- name: Undefine previous vm
  community.libvirt.virt:
    command: undefine
    name: "{{ item.name }}_{{ cluster_name }}"
    uri: "{{ libvirt_uri }}"
  ignore_errors: true
  with_items: "{{ groups['master_nodes'] }}"

- name: Create the qcow2 file
  command: "qemu-img create -f qcow2 /var/lib/libvirt/images/{{ item.name }}_{{ cluster_name }}.qcow2 50G"
  with_items: "{{ groups['master_nodes'] }}"

- name: Create vm
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', '{{ role_path }}/templates/ai-vm.xml') }}"
    autostart: yes
    uri: "{{ libvirt_uri }}"
  with_items: "{{ groups['master_nodes'] }}"

- name: Start vm
  community.libvirt.virt:
    command: start
    name: "{{ item.name }}_{{ cluster_name }}"
    uri: "{{ libvirt_uri }}"
  with_items: "{{ groups['master_nodes'] }}"
