---
- name: Ensure extra manifests path exists
  file:
    path: "{{ manifests_path }}"
    state: directory

- name: Create the workload-partitioning MachineConfig manifest
  template:
    src: templates/02-master-workload-partitioning.yaml
    dest: "{{ manifests_path }}/02-master-workload-partitioning.yaml"
  when: management_workload_cpuset != ''
